// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCr0_Ay7DbQtbd29J3yNxov3_6hhJZ4HY',
    appId: '1:382185239274:web:8676ad08fb7a0c389c9d93',
    messagingSenderId: '382185239274',
    projectId: 'horas-v1-f02a7',
    authDomain: 'horas-v1-f02a7.firebaseapp.com',
    storageBucket: 'horas-v1-f02a7.firebasestorage.app',
    measurementId: 'G-Z0GC92VNQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgpEJsLbgbgquT13jriFsvXlLwpUsdwaE',
    appId: '1:382185239274:android:a43e2678bc0a50209c9d93',
    messagingSenderId: '382185239274',
    projectId: 'horas-v1-f02a7',
    storageBucket: 'horas-v1-f02a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtuX-KKJDHU1Wvwbl3hIjhLtXDejBrTM8',
    appId: '1:382185239274:ios:1ab641e851f738759c9d93',
    messagingSenderId: '382185239274',
    projectId: 'horas-v1-f02a7',
    storageBucket: 'horas-v1-f02a7.firebasestorage.app',
    iosBundleId: 'com.example.routePlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtuX-KKJDHU1Wvwbl3hIjhLtXDejBrTM8',
    appId: '1:382185239274:ios:1ab641e851f738759c9d93',
    messagingSenderId: '382185239274',
    projectId: 'horas-v1-f02a7',
    storageBucket: 'horas-v1-f02a7.firebasestorage.app',
    iosBundleId: 'com.example.routePlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCr0_Ay7DbQtbd29J3yNxov3_6hhJZ4HY',
    appId: '1:382185239274:web:4224bd1bc37b1b469c9d93',
    messagingSenderId: '382185239274',
    projectId: 'horas-v1-f02a7',
    authDomain: 'horas-v1-f02a7.firebaseapp.com',
    storageBucket: 'horas-v1-f02a7.firebasestorage.app',
    measurementId: 'G-4LG4JR0MVZ',
  );
}
